document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<title>在线开放课程平台</title>");
document.writeln("	<link rel=\'stylesheet\' type=\'text/css\' href=\'css/header.css\'>");
document.writeln("	<link rel=\'stylesheet\' type=\'text/css\' href=\'css/index.css\'>");
document.writeln("	<link rel=\'stylesheet\' type=\'text/css\' href=\'css/scroll.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<!-- 导航开始 -->");
document.writeln("<div class=\'menu\'>");
document.writeln("	<ul id=\'nav\'>");
document.writeln("		<li><a href=\'../index.html\'>网站首页</a></li>");
document.writeln("		<li>");
document.writeln("			<a href=\'../course_overview/course_introduction.html\'>课程概况</a>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'../course_overview/course_introduction.html\'>课程简介</a></li>");
document.writeln("				<li><a href=\'../course_overview/course_feature.html\'>课程特色</a></li>");
document.writeln("				<li><a href=\'../course_overview/reference_data.html\'>教材与参考资料</a></li>");
document.writeln("				<li><a href=\'../course_overview/history.html\'>历史沿革</a></li> ");
document.writeln("			</ul>");
document.writeln("		</li>");
document.writeln("		<li>");
document.writeln("			<a href=\'../teacher_team/teach_director.html\'>教师队伍</a>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'../teacher_team/teach_director.html\'>课程负责人</a></li>");
document.writeln("				<li><a href=\'../teacher_team/course_team.html\'>课程教学团队</a></li>");
document.writeln("				<li><a href=\'../teacher_team/main-teacher.html\'>主讲教师</a></li>");
document.writeln("				<li><a href=\'../teacher_team/young_teacher.html\'>青年教师培养</a></li> ");
document.writeln("			</ul>");
document.writeln("		</li>");
document.writeln("		<li>");
document.writeln("			<a href=\'../teach_arrangement/teach_outline.html\'>教学安排</a>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'../teach_arrangement/teach_outline.html\'>教学大纲</a></li>");
document.writeln("				<li><a href=\'../teach_arrangement/teach_calender.html\'>教学日历</a></li>");
document.writeln("				<li><a href=\'../teach_arrangement/teach_content.html\'>教学内容</a></li>");
document.writeln("				<li><a href=\'../teach_arrangement/teach_plan.html\'>授课计划</a></li>");
document.writeln("				<li><a href=\'../teach_arrangement/teach_point.html\'>教学难重点</a></li>");
document.writeln("				<li><a href=\'../teach_arrangement/teach_method.html\'>教学方法与手段</a></li>");
document.writeln("			</ul>");
document.writeln("		</li>");
document.writeln("		<li>");
document.writeln("			<a href=\'../teach_reform/reform_mesure.html\'>教学研究改革</a>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'../teach_reform/reform_mesure.html\'>教学改革措施</a></li>");
document.writeln("				<li><a href=\'../teach_reform/reform_project.html\'>教学改革立项</a></li>");
document.writeln("				<li><a href=\'../teach_reform/reform_achievement.html\'>教学改革成果</a></li>");
document.writeln("				<li><a href=\'../teach_reform/teach_award.html\'>教学表彰和奖励</a></li> ");
document.writeln("			</ul>");
document.writeln("		</li>");
document.writeln("		<li>");
document.writeln("			<a href=\'../teach_resource/courseware.html\'>教学资源</a>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'../teach_resource/courseware.html\'>课程课件</a></li>");
document.writeln("				<li><a href=\'../teach_resource/course_vedio.html\'>教学录像</a></li>");
document.writeln("				<li><a href=\'../teach_resource/exercise.html\'>习题库</a></li>");
document.writeln("				<li><a href=\'../teach_resource/demo.html\'>案例库</a></li>");
document.writeln("				<li><a href=\'../teach_resource/task.html\'>实验任务</a></li>");
document.writeln("				<li><a href=\'../teach_resource/document.html\'>技术文档范本</a></li>");
document.writeln("			</ul>");
document.writeln("		</li>");
document.writeln("		<li>");
document.writeln("			<a href=\'../teach_manage/open_plan.html\'>教学管理</a>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'../teach_manage/open_plan.html\'>开课计划</a></li>");
document.writeln("				<li><a href=\'../teach_manage/class.html\'>上课班级</a></li>");
document.writeln("				<li><a href=\'../teach_manage/roster.html\'>班级花名册</a></li>");
document.writeln("				<li><a href=\'../teach_manage/grade_list.html\'>班级成绩单</a></li> ");
document.writeln("				<li><a href=\'../teach_manage/homework_demo.html\'>学生作业案例</a></li>");
document.writeln("			</ul>");
document.writeln("		</li>");
document.writeln("		<li>");
document.writeln("			<a href=\'../teach_result/out_evaluate.html\'>教学效果</a>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'../teach_result/out_evaluate.html\'>校外专家评价</a></li>");
document.writeln("				<li><a href=\'../teach_result/in_evaluate.html\'>校内督导评价</a></li>");
document.writeln("				<li><a href=\'../teach_result/self_evaluate.html\'>教师自我评价</a></li>");
document.writeln("				<li><a href=\'../teach_result/student_evaluate.html\'>校内学生评价</a></li> ");
document.writeln("				<li><a href=\'../teach_result/social_evaluate.html\'>社会评价</a></li>");
document.writeln("				<li><a href=\'../teach_result/evaluate_file.html\'>教学评估及相关文件</a></li>");
document.writeln("			</ul>");
document.writeln("		</li>");
document.writeln("		<li>");
document.writeln("			<a href=\'../teach_interact/wechat.html\'>教学互动</a>");
document.writeln("			<ul>");
document.writeln("				<li><a href=\'../teach_interact/wechat.html\'>微信群</a></li>");
document.writeln("				<li><a href=\'../teach_interact/qq.html\'>QQ群</a></li>");
document.writeln("				<li><a href=\'../teach_interact/interact.html\'>网站内的师生互动</a></li>");
document.writeln("			</ul>");
document.writeln("		</li>");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<!-- 导航结束 -->");